### ISSUE TITLE
Setting willReadFrequently on layers created/managed by Konva?

### ISSUE THREAD

**Issue by jez9999** [konvajs/konva#1417]
I'm getting the following warning appearing in the console when I mouse over my Konva canvas:

> Canvas2D: Multiple readback operations using getImageData are faster with the willReadFrequently attribute set to true. See: https://html.spec.whatwg.org/multipage/canvas.html#concept-canvas-will-read-frequently

Is there a way to get Konva to create its canvas objects with `willReadFrequently` set to avoid the warning?  If not could this be added?

**Comment by ivanbacher** [comment]
+1

**Comment by meghe2000** [comment]
![image](https://user-images.githubusercontent.com/85949855/193571167-11a0f700-7bff-4893-8f10-ce41b3b9fdac.png)

I have the same problem.

**Comment by lavrton** [comment]
Should be resolved with `konva@8.3.13`

**Comment by RamiAlzayat** [comment]
@lavrton  I'm not 100% if its the same issue, but its still happenning in `konva@8.3.13`

![Screenshot 2022-10-24 at 16 27 42](https://user-images.githubusercontent.com/18601660/197550450-a6d27893-0d0c-4699-b80b-804752265cc2.png)

![image](https://user-images.githubusercontent.com/18601660/197550513-ba89ca3e-93c4-4ade-95f0-1bf751c6bdec.png)

Thank you for the effort!

**Comment by sndyuk** [comment]
@lavrton Is there any reason it doesn't have `willReadFrequently` option?
https://github.com/konvajs/konva/commit/3e749e1ea86c3b6289b1b501e459cff73b775f45#diff-f7f997285badba150383cf0b6bf96a9cf401a35da9cf856968de517ee01aab82R718

**Comment by lavrton** [comment]
Cached canvas don't have this option. Need to think how to enable it just there (but not for main scene canvas of layer). Happy to apply PR.

**Comment by yc-yangchen** [comment]
+1
