### ISSUE TITLE
getIntersection broken on Safari iOS10 iPad

### ISSUE THREAD

**Issue by denweng** [konvajs/konva#187]
Just want to inform you.
We had a problem with kineticjs which is in conva too.

To test open your srag stars demo on an iPad with iOS10 (we tested on an early iPad Air).
Random Stars will be not draggable.

best regards Tobias & Dennis from SinusQuadrat

Reason:
`getImageData `gives back wrong colors in Safari iOS10 iPad.
Colors values higher than 240 differ 1 from the originaly set value. This breaks the function of hitCanvas and colorIndex / coloKey and getIntersection.

Our solution in kineticjs is to use ios save colors for identifiers:
```
getRandomColor: function(iosSave) {
    var randColor;
    if(iosSave){
        randColor = (Math.random() * 0xadcea0 << 0).toString(15);
    }else{
        randColor = (Math.random() * 0xFFFFFF << 0).toString(16);
    }
    while (randColor.length < 6) {
        randColor = ZERO + randColor;
    }
    return HASH + randColor;
}
```

to test independet (canvas in html needed, loggs differing values):
```
dndcanvas = document.getElementById("dndcanvas");
var ctx = dndcanvas.getContext('2d');
ctx.clearRect(0, 0, dndcanvas.width, dndcanvas.height);

for (var i = 0; i <= 255; i++) {
    ctx.fillStyle = 'rgb(230,230,' + i + ')';
    ctx.fillRect(i, canvasObj.y-35, 1, 1);
    var p = ctx.getImageData(i, canvasObj.y-35, 1, 1).data;
    if (i != p[2]) {
        console.log(p[2]);
    }
}
```

**Comment by lavrton** [comment]
@denweng  Thanks for the report! I can reproduce on iPad. As far as I can see `getImageData` broken only for some colors, not all, correct?
What is " ios save colors"? Just our of curiosity, how do you found the solution?
```
if(iosSave){
        randColor = (Math.random() * 0xadcea0 << 0).toString(15);
    }else{
        randColor = (Math.random() * 0xFFFFFF << 0).toString(16);
    }
    while (randColor.length < 6) {
        randColor = ZERO + randColor;
    }
```

Can we use `iosSave = true` always?

**Comment by denweng** [comment]
@lavrton Only colors with one or more values above 240 0xF? (r g b) are broken.
We implemented the switch iosSave to call it with this to generate the color ids. We wanted to keep the possibility to get a fully random color for other cases.
To avoid Fs in the hex we choose 15 as base.

In the context of the colorKeys always use iosSave=true

Dennis

**Comment by lavrton** [comment]
I can't reproduce the bug in last safari version. Looks like it is resolved.

**Comment by sjaq** [comment]
Can confirm this is still an issue with IOS and monkeypatching konva with the fix as stated above fixed my issue.

Using konva version 1.7.6.


```
// Monkeypatch for IOS
import { Util } from 'konva';
Util.getRandomColor = () => {
  var randColor = ((Math.random() * 0xadcea0) << 0).toString(15);
  while (randColor.length < 6) {
    randColor = `0${randColor}`;
  }

  return `#${randColor}`;
}
```

**Comment by david-banks-roam** [comment]
Experiencing this exact same issue with Konva 3.3.3 / iOS Safari 12.1
