### ISSUE TITLE
Problem with JSDom higher than 3.0

### ISSUE THREAD

**Issue by kudlajz** [konvajs/konva#254]
Hey there!

We are currently using `canvas@1.6.5`, `konva@1.5.0` and `jsdom@3.1.2`, but we need to upgrade our NodeJS to version 7, which prevents us from using `jsdom` (because of its `contextify` dependency).

Problem is, when we update the `jsdom` to a higher version (for example `8.5.0`), we start getting

    ctx.drawImage(layerCanvas, 0, 0, width, height)
    ^

    TypeError: Image or Canvas expected

Is there something wrong with our code? Minimal code required to reproduce this problem [can be found here](https://github.com/kudlajz/canvas-problem/blob/master/index.js). We are grateful for any input as I have spent several hours trying to resolve this issue with no luck and from the konva's readme, jsdom@8.5.0 should be supported. I am using macOS 10.12.6 and node 6.9.1.

If I should rather create the issue in node-canvas repository or jsdom, please, let me know.

**Comment by lavrton** [comment]
@kudlajz Hi. I just pushed some fixes for last versions of `jsdom` and `node-canvas`. Can you try it? You can install directly from repo (new version is not published yet).

**Comment by kudlajz** [comment]
@lavrton Unfortunately, that did not help. It is still throwing the same error 😞

**Comment by lavrton** [comment]
@kudlajz did you try the last version from the repo?

**Comment by kudlajz** [comment]
@lavrton Yes, I have cloned konva's master branch.

**Comment by kudlajz** [comment]
It seems I have resolved the issue.. instead of importing `node-canvas`, one has to use `new Konva._nodeCanvas()` or `new Konva.window.Image()`. Can you publish a new version, please? Thanks.

**Comment by kudlajz** [comment]
@lavrton It seems I have resolved the issue.. instead of importing `node-canvas`, one has to use `new Konva._nodeCanvas()` or `new Konva.window.Image()`. Can you publish a new version, please? Thanks.

Note: When I try the same approach with currently published Konva (and JSDOM 8.5), it does not work.

**Comment by kudlajz** [comment]
@lavrton Can you publish a new version with the fix?

**Comment by lavrton** [comment]
Done. I am closing this issue for now.
Please add a comment if you still have issues.

**Comment by kudlajz** [comment]
@lavrton Thanks, but I can't see the version 1.6.8 in npm, only 1.6.7.

**Comment by lavrton** [comment]
Oops. Sorry. Try now. Should be ok.
